# docker-compose.yml
version: '3'

services:
    portainer:
        container_name: portainer
        image: portainer/portainer:1.24.0
        restart: always
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer-data:/data
        logging:
            options:
                max-size: 10m

volumes:
    portainer-data:
        name: portainer-data
        driver: local-persist
        driver_opts:
            mountpoint: "${PERSIST_DATA_PATH}/data/portainer-data"